name: node-sse-dev

services:
  backend:
    container_name: node-sse-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: development
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - ../logs:/app/logs
      - node_modules:/app/node_modules
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - TZ=Asia/Kuala_Lumpur
    depends_on:
      - redis-stack
    restart: unless-stopped
    networks:
      - network

  redis-stack:
    container_name: node-sse-dev-redis
    image: "redis/redis-stack:latest"
    ports:
      - "8001:8001" # UI
      # - "6379:6379" # Redis port
    restart: unless-stopped
    networks:
      - network

networks:
  network:

volumes:
  node_modules:
