name: node-sse

services:
  backend:
    container_name: node-sse-fastify
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: production
    ports:
      - "3000:3000"
    volumes:
      - ../logs:/app/logs
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - TZ=Asia/Kuala_Lumpur
    depends_on:
      - redis-stack
    restart: unless-stopped
    networks:
      - network

  redis-stack:
    container_name: node-sse-redis
    image: "redis/redis-stack:latest"
    ports:
      - "8001:8001" # UI
      # - "6379:6379" # Redis port
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - network

networks:
  network:

volumes:
  redis-data:
